---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-core
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  path: ./infrastructure/k3d-cilium/crossplane/core
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: crossplane
      namespace: crossplane-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-provider
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./infrastructure/k3d-cilium/crossplane/provider
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crossplane-core
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-configuration
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./infrastructure/k3d-cilium/crossplane/configuration
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crossplane-provider
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-custom-resources
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  path: ./infrastructure/k3d-cilium/custom-resources
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crossplane-configuration
