apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      version: "1.12.0"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    # Performances
    bpf:
      preallocateMaps: true
    tunnel: disabled
    bandwidthManager: true
    installNoConntrackIptablesRules: true
    kubeProxyReplacement: strict
    # GKE
    gke:
      enabled: true
    ipam:
      mode: kubernetes
    cni:
      binPath: "/home/kubernetes/bin"
    ipv4NativeRoutingCIDR: "10.144.0.0/14"
    resources:
      requests:
        cpu: 120m
      limits:
        memory: 192Mi
    nodeinit:
      enabled: true
      reconfigureKubelet: true
      removeCbrBridge: true
      priorityClassName: system-cluster-critical
      resources:
        requests:
          cpu: 50m
        limits:
          memory: 50Mi
    operator:
      replicas: 3
      resources:
        requests:
          cpu: 50m
        limits:
          memory: 80Mi
      rollOutPods: true # Reload pods when the configmap is updated
