apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: observability
      version: "37.2.0"
  interval: 10m0s
  timeout: 30m
  install:
    remediation:
      retries: 3
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    commonLabels:
      prometheus-instance: "main"
    # Disabling  of components that are managed by the Cloud provider
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false

    kube-state-metrics:
      prometheus:
        monitor:
          additionalLabels:
            prometheus-instance: main

    prometheusOperator:
      resources:
        requests:
          cpu: 150m
        limits:
          memory: 256Mi
      configReloaderCpu: 100m

    alertmanager:
      # This is just a dev cluster ;)
      enabled: false

    prometheus:
      prometheusSpec:
        serviceMonitorSelector:
          matchLabels:
            prometheus-instance: "main"
        podMonitorSelector:
          matchLabels:
            prometheus-instance: "main"
        ruleSelector:
          matchLabels:
            prometheus-instance: main

    grafana:
      admin:
        existingSecret: "kube-prometheus-stack-grafana"
        userKey: admin-user
        passwordKey: admin-password
      resources:
        requests:
          cpu: 100m
        limits:
          memory: 256Mi
