apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      version: "2.4.0"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    fullnameOverride: sealed-secrets-controller
    resources:
      requests:
        cpu: 80m
        memory: 100Mi
