apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kube-prometheus-stack-grafana
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBUUUoy7TKch72kSV4Qm2lV20QbblSv4+ir8AopqYe2BTXCh2CJng+omtINLaXVOZl8y/u9qnrByazrO5pVK3MjxUVDhEZwmQNzFQJKT3EvIP6WpbssRhUAzWORxLc8VLitnFCNmNVbo+m9lNP80unwnSkWweUaUJE+vTn38vEIRJqA9Qv5HHTzWZANfR0ofkQdoXQCH89b1V7r5MtyjnZN6bQ951oup+pWrZZTwUciR57BYKb8+hdB2fatJAtq9bO37eaJ4tNo7SCXtQv6c+thkVoUt3muLk50wgDlvSrZVLHFDaAdNPYZoFejf4+NRA1LJJhU+T+oNV7/weBJNWV1NGUSpX4W/IhHlJB8JoMYKFiP57kFejdeF92GEWvi+YufSg1PXoDbQTmDwKkcwn0cY7o2VhCDSAjhzubI3XqjjEH7vIPrq5PmWcqsdZ7GjIY8ayXDTtFzCx5s37Di5cYM5KZoY/9nAWYgR+9bjtKrPO0MxCwvMf7IRPmSwIFOLB+NpU96rbUOoDOEL9wjekrU4dFGvfvzauEH/aH883QDQByrDOFNh/Ffxg2sPu0nCpPFJ53rDmi+lX+dVVG+sHTrcaK5WXxN4VFC6zPL+sOsJZKF8Pgj8FLTqW9beVXAjPyt4GMEbZoDI/+nda0znqoHMYei0ys2MmV4qtfcQqk3eDdycQ7yLMEnjZ2SLfJ52AU1Tcd3w/9Vag==
    admin-user: AgB/lD4OGqAnI2lfleBP8+h49MhPZaCbn5hkalFFONrI5Ayreh72TUKQVBVSYihObsiaE4TwPj/NnvwtKddr1g4Ob/+MgbSlGfwJD6wUzI9TrZxn7bzNgq5FYyQtrhXw+HJqbmZZ4ZS1PTNDi18WSJCYp4cJzqmutwIXKnO86TX2iDjw46hyE9zjZ0dbNY4209A7JzBIENJUfqMBHuJH4uBMUMePrGfEqqtnfY/uRiDaca5ZvJ/6VE81jbSE8YqjeTFyr5OB3sAQWD0txCPHN+6xN9x9CTorr/JWyHiLVawWteyvVapXBdcgQ+uY36jKH/sUHPp0rb+yB0E4UKkjxy3R8y3/mnclhkfmuqVYWJFjMXgW/IA/rsbKJcvIqc7qVSwCrB/YqPuF9AaYGNxu/9ZCEZ6a6xaLBHChIBICZPdemLmqsyqapm7FMOOG8+BJwcxNfqX/y0vlqM1KP7TEeSLK3hHLYOX4m0hYZH50i3bcFL4wFUvIhNFkKgp+PAhanv1xNXaQgUn3oQFsII7VH2NjtH0y6ZXGwHviwn7bk9nxFsrwIJkKwReaLX9juLKqk7U6RfEjAicSkbN6yCaSnVwhAGAiLJse6QswhNxM9WscV0tE2xcNA7Xy6+AbxvYTC11NOi5aaUkEi6kVoffQN+r3+QJuo0fK58bre3rJAQEpBesdEEtSnpUdQESY7dlDI1Pod59wXQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: kube-prometheus-stack-grafana
      namespace: observability

