apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kube-prometheus-stack-grafana
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCAYt2rJxoXyLLUJyAOI+FkWFf0e8jUvfHaNo2rlsb/a50sIYSVNMBEQYXyEk8KAywoCd81zZbMp5HuSk3RagCOglBqyz9n+ruDVbA+Zgwdqlj09e3P8U5RrQFjXZgxIkfDFNWLXngS4GiTWX/nBnN7ZrDP4QtoNiKj0JIy8gmaUApoR/2zRDH5wwnaUWTWn2JA3CCCNFY8MfCriWFCuHrBY9zN5iaxR3f16bZaS8HhJ4L8KQwEinhQOZWrjVn+DS1M9XcH59hP0MicD5xRovqRzWNqZ6NlRaT9/eE3Y9FEzJMPBx7aLEgAkLcQo++hLyKeNaDwLQK7m8yUbR7d5yopSFH9aLdFzIZes2xbTXBAO3rTNho1Bn9v48K4kJ9ZNujhJ12OPV6VOaC/cNXG0FLnQ3BzzYy1kUAYtS51QV+pvsMVXgbHYpE+fzTLDZJoxexVv22zCrYOCDhLe2kyYb2QLjyqkTX+ZKn20I3oSDBqgaYrwYPpmJJ0ugkF0ULow2juMvNWCgJFE3yR+7H7wjpYRv6EeLz6DgZMlv6J70dAR4AxahlH8A5iBOJEyde9Q8gc42PeUFfVQbLszxsHc61NtjDphtPsoSAVs0ZuxVPeYPqJTfRve0VQzXiOoH6XT2ieTcq7R1pTMaGNmZU9p6wnrV6aZePPYn6l2xsnKuPZsHbgpemR/+FG8g2ox/IWJvqG8xk5mnedVA==
    admin-user: AgAQLQA5rW8d5V6nqgK4vTeNJspL9EI/kSn183pNWUDepdmZQf/6QIK+MIq4y3ex0WjKaDs6jYArCGsdGFgDi02cUqIzT2iLiBom+zgNY4AFy6suRR5+OQmnUxU0D9XWn5wO8Kb/q1kFjHfAekg1IxrmHWGmIz+4n8AogESTUBoE1dTJ+1bXOBqZsdCHFRTKXajDWeQYQq3JfSP1PypG+sJOMRXwUzOAwdLy5E9Rb1bNk1xwwibptbP35kLl4INpofe5jfXefgc+wBjV/b5xuuhMsgjbsx2u+OGr+ejgBrgrMCLQBz2CW6vHwAOW1Ip5q/QchizYfDhfAKvd77ZUs3wBolPhWxg9nu4LCkoEjrDkrwPi6mlokRrWlQZ6lDVdHHuAd2MnxTF8tGU+rIp7z9t0xk6ffMj7JMYacMWq0vajiBCnED0krB4iXrxJbx36/v35rhClEKUfNhPf45rhy8G0NcxpJXpUkQYwd/X3Ur5TkT9/wKm87uvhB2FSqHRMUNefZdDbhf2l2mB2BmQaDOg+5KOjSffzbVntWE682Q890qDhkIPmgecGwPL0a6Z037EyNIu7y71CK1O5gvYMxqRTzj4wnm6y0jS/SoX0yJYTYEHp8mN2m+FBC0OswbMlg3rxZ+QqnLL0HFfE3WekHzABYPRqwaxXj7MI+zo42M5JLAZ09hCWJGlAkNJsmHtxIKOoATlW9A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: kube-prometheus-stack-grafana
      namespace: observability

