apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kube-prometheus-stack-grafana
  namespace: observability
spec:
  encryptedData:
    admin-password: AgA934qZTheisvcQDRz+/3eSp29znEh5fUBY82xCo8mNQMhezgJBpl7VMBylgYpiKihXA0kNCSGg96SSPGVQftLCZzqzP0ReR9Gj5OABVG++na/zEACjg72zI2keL/Df5lNi4Bh0mTP4VJpUf79Bmb1N1ZnjvPPqu1JVTFzOCwPs8AkVoIb7hw+3EWrkJXZbxaXbsp/1ic4F1/PQsIr6wa7vBGQfk5hNFcjFGWInLq48cGPx1ez3tkNAOrdbaIvKg7dB++GvrK1B68iKgwDOVSo3Eht6B39d315zjdXzSlIychoTqbOa7M8LIi7agjDDz3dknIqwz8e70sL2CeoVG2o0O62ghdKjfuovy73+3bk1obD9mSXVA9Ju97ho6TSK1HHB5/UmMmxmdECepI/lgtwvawtWYPo6fx3acb6yTAOJ5HS8fa5BCQlyczSQhz1HGHrEuQWG4dVFInI2UiQoF98K22C6eZ4dNJDQalslzP+tFy7cTRXWPyGujMtojquchBLWEfnEBo+pl6bkbrr0lvHH5UyQ0M90scDmRqxOxdbq+Ho+nCBJJj324nqTwKtKYH90eQN4at5dJDYVpR8if+gCk0z23grxxIoYCRn717xRouLMUtbBempXXkjQv7ccUpKZSsdkG0BY19t7dIr8ZVtgF27hEJnDl3ruhFFXxzLzla5OhkHKShoq14iZX/L0FtMwhEIh4sF6zw==
    admin-user: AgBiksR3dFO0qxOku4y3Qlq5oWMXYHisqHXo4+ByStIf4TxDp0i4ReBSfIsZ9s2wckRZVnq+5LMQSleMpw84Wd8qegTNJVQjrN1GAp3bFgn5qYajPB4bP4/vd7EBrnqALwHGH3YGMhllxUahr6+T4t+pLhf0auDFtl/vDDhwStkWqwtdamkOvNo+hddFmYACh8+DAWaw5uMb7HcU16xj5lJ6bYZHA2sW3Dsf7X4ElW5HGH+bs3Gt1u4F0OQNnYrrj+hnaZgiCb5GUtvHis60Tu5n4GOXb8cxrZSEO5Xpt/Pvl0XjPhaXqehBHpOJE+eDyEYGMX9pGWBaEbGozkEzRtcsHTKXro/PR6S2Evmjm+QaJUVPjgzI9Lucklz2Y6Arp6oM/6ChbrVVt1i8HAZt4CgbSuCXLtVL5hecZCBjQnLFvmbr2OSVwG7PKLoOLa77NvcSfqz1hDJEEI258kwisvluJDTULA8SWHx0IpwFiJQ1bY4YUTke7LYxkW8cYH8quUk1y1sQT0wEZVxfDoFaHsqjKqsN7WMtYw/IJImfk+/bk8mjFg7wA3r5clF2qyyyEAkXE0340N/jYlQq3VfqAQ9PdVnYDBU72vT+7QLFyH5ApTO+OoOZHPBvC5666IsqsFGNxv2G5SwNEW07hiHm+osYNu24Lh1sRF3nJlK30otmQD4hyfPRcxx8L/RJQcu2BiVvZtGASg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: kube-prometheus-stack-grafana
      namespace: observability

